#!/bin/bash

# Directory to save the extracted files
save_directory="files"

# Create the save directory if it doesn't exist
mkdir -p "$save_directory"

# Read the list of changed objects from standard input
while read oldrev newrev refname; do
  # Get the list of changed files
  changed_files=$(git diff-tree --name-only --diff-filter=ACMRT $oldrev $newrev)

  # Iterate over each changed file
  while read -r file; do
    echo "Changed file: $file"
    # Extract the file to the save directory
    git cat-file -p $newrev:"$file" > "$save_directory/$file"

  done <<< "$changed_files"

done